### ISSUE TITLE
Prikaz regij

### ISSUE THREAD

**Issue by ines-silc** [ines-silc/APPR-2017-18#2]
Pri izrisovanju zemljevida mi izginejo dve regiji. Moja koda:

voda <- poraba_vode %>% group_by(regija) %>% summarise(poraba_vode = mean(poraba_vode))
zemljevid.vode <- ggplot() +
  geom_polygon(data = voda %>% right_join(zemljevid, by = c("regija" = "NAME_1")),
               aes(x = long, y = lat, group = group, fill = poraba_vode), color = "black")+
               xlab("") + ylab("") + ggtitle("Poraba vode po regijah")

Za pomoč se že vnaprej zahvaljujem.

![poraba vode](https://user-images.githubusercontent.com/28105590/34792645-01e326ee-f649-11e7-80ca-867840368cbc.png)

**Comment by jaanos** [comment]
Problem se pojavi, ker imaš v podatkih ti dve regiji drugače poimenovani kot v zemljevidu. Glede na to, da imaš ista imena v vseh podatkih, bo najlažje, če zamenjavo opraviš kar v zemljevidu:
```R
levels(zemljevid$NAME_1)[levels(zemljevid$NAME_1) %in%
                           c("Notranjsko-kraška",
                             "Spodnjeposavska")] <- c("Primorsko-notranjska",
                                                      "Posavska")
```
