### ISSUE TITLE
Težava pri urejanju tabele

### ISSUE THREAD

**Issue by ines-silc** [ines-silc/APPR-2017-18#3]
Pri tabeli, ki vsebuje podatke o življenjski dobi, so zaradi vira podatki urejeni kot dve leti skupaj (npr. 2000-2001).  Želela bi, da se ohrani samo drugo leto.

Hvala za pomoč
![doba](https://user-images.githubusercontent.com/28105590/35752374-0558a680-085c-11e8-9384-b4d744dbc52c.png)

**Comment by jaanos** [comment]
Glede na to, da te zanimajo številke na začetku vsakega niza, bo najlažje, če uporabiš kar `parse_number`:
```R
tabela$leto <- parse_number(tabela$leto)
```
