### ISSUE TITLE
Dodajanje Shiny-ja v poročilo

### ISSUE THREAD

**Issue by ines-silc** [ines-silc/APPR-2017-18#4]
Imam problem pri dodajanju shinyja v poročilo. Brez njega se poročilo lepo prevede in se vsi graf pokažejo, ko pa dodam shiny sam normalno deluje, vendar vsi grafi, ki niso v shiny-ju izginejo.

Zahvaljujem se Vam za pomoč.

**Comment by jaanos** [comment]
Zanimivo, pri meni vse deluje. Ali se isto zgodi, če poročilo odpreš v brskalniku (levo zgoraj imaš gumb *Open in Browser*)?

Kar lahko poskusiš, je, da znova namestiš knjižnici `shiny` in `knitr`.

**Comment by ines-silc** [comment]
Sem znova namestila paketa, a ni spremembe. Če poročilo odprem v brskalniku prav tako ne pokaže grafov.
![rstudio primer](https://user-images.githubusercontent.com/28105590/36026635-48845490-0d98-11e8-872d-9d37470eb4b1.jpg)
![shiny splet](https://user-images.githubusercontent.com/28105590/36026643-4bd546cc-0d98-11e8-976b-af2afb52345a.jpg)

**Comment by jaanos** [comment]
Najbližje, kar sem našel, je rstudio/rmarkdown#210 in rstudio/rmarkdown#1197. Tako bi svetoval, da najprej poskusiš posodobiti še knjižnico `rmarkdown`, če pa to ne bi delovalo, lahko poskusiš namestiti še knjižnici `httpuv` in `caTools`. Po vsaki novi namestitvi knjižnice znova zaženi RStudio, saj bi to morda lahko vplivalo na prevajanje.

**Comment by ines-silc** [comment]
Sem posodobila knjižnico 'rmakrdown' in dodala knjižnici 'httpuv' in 'caTools'. Napaka se ne odpravi, pri prevodu se pojavi pojavno okno:
![napaka](https://user-images.githubusercontent.com/28105590/36045169-20bb2316-0dd5-11e8-84ab-93bd608e24f2.jpg)
Če ne dovolim Shiny vmesnika se pojavi napaka "Shiny applications not supported in static R Markdown documents", če pa ga dovolim, vsi grafi izginejo, vmesnik pa normalno deluje.

**Comment by jaanos** [comment]
Glede na to, da pri meni deluje, enostavno poskrbi, da ti grafi delujejo v obliki HTML, ter da Shiny deluje, ko ga dovoliš. Vseeno pa iz poročila odstrani prvi dve vrstici, da ti bo pravilno oblikovalo naslov.
