### ISSUE TITLE
Zaključevanje projekta

### ISSUE THREAD

**Issue by ines-silc** [ines-silc/APPR-2017-18#5]
Pozdravljeni,
projekt sem dokončala in ga pošiljam v pregled.

Lep pozdrav

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjala, mi prosim javi, da posodobim povezavo.

Pripomnil bi samo to, da razpredelnice `tabela1`, `tabela2` in `tabela4`, ki jih opisuješ v poročilu, niso v obliki *tidy data*, saj imaš v istem stolpcu meritve na različnih lestvicah in z različnimi merskimi enotami. Tako imaš namesto `tabela1` razpredelnici `bdp` in `izdatki`, ki sta že v obliki *tidy data*, pri `tabela2` in `tabela4` pa pretvorba ni potrebna, saj imaš lahko vsako meritev v svojem stolpcu. Pri razpredelnici `tabela3` pa dveh stolpcev pri pretvorbi ne upoštevaš in zato ostaneta kot taka.

Opozoril bi tudi na oblikovanje seznamov v RMarkdownu. Za številčenjem pusti presledek, da se bo številčen seznam prepoznal kot tak - tam imaš lahko opis razpredelnice, tako da bo prvi stolpec pod prvo točko, npr.
```markdown
1. `bdp` - podatki o bruto domačem proizvodu

  - `Leto` - spremenljivka: leto, katerega so bile narejene meritve
  - `Bruto domači proizvod` - meritev: rast bruto domačega proizvoda (število)
  - `Dohodek` - meritev: povprečni dohodek na člana gospodinjstva (število)
```

**Comment by ines-silc** [comment]
Pozdravljeni, 
sem popravila tabele in izpis tabel v poročilu. Imam pa še vedno težavo pri prevodu samega poročila, saj se mi grafi ne izrisujejo. Ali predlagate še kakšne popravke pred končno oddajo projekta?

Lep pozdrav

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo. Drugih komentarjev nimam, žal pa tudi ne ideje, zakaj se grafi ne izrisujejo.
